name: Android CI

on:
  push:
    branches:
     - main   # اگر شاخه‌ات master هست اینو بکن master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4   # آخرین نسخه

      - name: Set up JDK 17
        uses: actions/setup-java@v4  # آخرین نسخه
        with:
          distribution: temurin
          java-version: 17

      - name: Give gradlew permission
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4   # به جای v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
